site_name: Critical Care Guidelines
site_url: https://critcare.net
site_dir: /tmp/rieapp_site
# bootstrap4 mkdocs readthedocs cinder
theme:
  name: cinder
  #name: bootstrap386
  custom_dir: themes/mods
# set `plugins: - search` to enable search, or `plugins: []` to disable
plugins: []
extra_templates: null
markdown_extensions:
  - md_in_html
  - markdown_include.include:
      base_path: docs

# nav tree
nav:
  - Home: /.
