name: make list

# Controls when the action will run.
on:
  schedule:
    - cron: '0 7-22 * * *'

  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  makelist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install setuptools
          pip install wheel
          pip install pdfminer.six
          pip install requests
          pip install mkdocs
          pip install markdown-include
          pip install mkdocs-cinder
          pip install PyPDF2

      - name: Download files
        run: |
          python .scripts/download.py -s "https://www.dropbox.com/sh/w9jw30h9bj5cbh2/AACEcqEc-_9Sl6J6g0pveapba?dl=0" -d "docs/1a74f8f7b8b7e871b413c4697f68b4401fbacdf0/criticalcare/" 

      - name: Make list
        run: |
          python .scripts/makelist.py -d "docs/1a74f8f7b8b7e871b413c4697f68b4401fbacdf0/criticalcare/" -p "docs/critcare_pub/criticalcare/" -e

      - name: Find duplicates
        run: |
          python .scripts/find_duplicates.py -s "docs/1a74f8f7b8b7e871b413c4697f68b4401fbacdf0/criticalcare/" 

      - name: Get review dates
        run: |
          python .scripts/get_review_dates.py -s "docs/1a74f8f7b8b7e871b413c4697f68b4401fbacdf0/criticalcare/" 

      - name: Get editors
        run: |
          python .scripts/get_editors.py -s "docs/1a74f8f7b8b7e871b413c4697f68b4401fbacdf0/criticalcare/" 

      - name: Commit pages if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -v docs/1a74f8f7b8b7e871b413c4697f68b4401fbacdf0/*
          git add -v docs/critcare_pub/*
          git diff-index --quiet HEAD || git commit -m "Automatically re-generate list and index"

      - name: Push pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run mkdocs
        run: mkdocs gh-deploy --force







